feat: authentication lib integration
bento-platform/bento_public pull request #150
Opened 2024-02-27 16:52 UTC by v-rocheleau

2024-03-12 20:53 UTC, v-rocheleau commented on package.json
> +    "bento-auth-js": "file:../packs/bento-auth-js-3.2.6.tgz",
TODO: replace with release from https://github.com/bento-platform/bento_auth_js/pull/22

2024-03-13 14:34 UTC, davidlougheed requested changes

2024-03-13 14:34 UTC, davidlougheed commented on src/js/components/Beacon/BeaconQueryUi.tsx
> +        styles={{
this object could be a constant itself (`CARD_STYLES` ?) in `beaconConstants` or somewhere

2024-03-13 14:34 UTC, davidlougheed commented on src/js/index.tsx
> +// TODO: replace HashRouter with BrowserRouter when we get rid of the golang server
not needed

2024-03-13 14:34 UTC, davidlougheed commented on src/js/types/services.ts
> +export enum Group {
this is overspecified I think

2024-03-13 14:34 UTC, davidlougheed commented on src/js/types/services.ts
> +export enum Name {
this is overspecified

2024-03-13 14:34 UTC, davidlougheed commented on src/js/types/services.ts
> +  MailtoInfoC3GCA = 'mailto:info@c3g.ca',
this is overspecified

2024-03-13 14:34 UTC, davidlougheed commented on webpack.config.js
>  // const webpack = require('webpack'); // only add this if you don't have yet
remove and replace with require(webpack) below

2024-03-13 14:34 UTC, davidlougheed commented on src/js/components/TabbedDashboard.tsx
> +    return <div />;
maybe return the SitePageLoading component instead?

2024-03-13 14:34 UTC, davidlougheed commented on src/js/components/TabbedDashboard.tsx
> +import { useAutoAuthenticate, useIsAuthenticated } from 'bento-auth-js';
move up above local imports

2024-03-13 14:34 UTC, davidlougheed commented on src/js/components/SitePageLoading.tsx
> +      <SiteHeader />
it doesn't make sense to render SiteHeader here based on the context of where it's used - it will just double-render SiteHeader

2024-03-13 14:34 UTC, davidlougheed commented on src/js/components/SiteHeader.tsx
> +  const isAuthenticated = getIsAuthenticated(idTokenContents);
I think there's a hook for this - `useIsAuthenticated`

2024-03-13 14:34 UTC, davidlougheed commented on src/js/components/SiteHeader.tsx
> +  const clientName = CLIENT_NAME;
these 3 are useless variable assignments

2024-03-13 14:34 UTC, davidlougheed commented on src/js/components/Beacon/BeaconQueryUi.tsx
> +import { getIsAuthenticated } from 'bento-auth-js';
move up above local imports

2024-03-13 14:34 UTC, davidlougheed commented on .gitignore
> +yalc.lock
missing trailing newline

2024-03-14 17:23 UTC, davidlougheed requested changes

2024-03-14 17:23 UTC, davidlougheed commented on src/js/index.tsx
> +        title={'You have been signed out'}
Add this to translation now so we don't forget about it later

2024-03-14 17:23 UTC, davidlougheed commented on src/js/index.tsx
> +        Please <a onClick={openSignInWindow}>sign in</a> to the research portal.
body needs translation - not sure how we do interspersed `<a>`...

2024-03-14 17:23 UTC, davidlougheed commented on src/js/store.ts
> +import { ToolkitStore } from '@reduxjs/toolkit/dist/configureStore';
move above local imports with other redux imports

2024-03-14 17:23 UTC, davidlougheed commented on src/js/types/services.ts
> +  Dev = 'dev',
missing prod environment

2024-03-18 14:55 UTC, davidlougheed requested changes

2024-03-18 14:55 UTC, davidlougheed commented on src/js/features/beacon/beaconQuery.store.ts
> +import { makeAuthorizationHeader } from 'bento-auth-js';
move this up with non-local imports

2024-03-18 14:55 UTC, davidlougheed commented on src/js/features/beacon/beaconQuery.store.ts
> +  const beaconIndividualsEndpoint = BEACON_URL + '/individuals';
this constant could be moved out of the function definition

2024-03-18 14:55 UTC, davidlougheed commented on src/js/hooks.ts
> +import { RESOURCE_EVERYTHING, Resource, queryData, useHasResourcePermission } from 'bento-auth-js';
move this above local imports

2024-03-18 14:55 UTC, davidlougheed commented on src/js/hooks.ts
> +import { useEffect } from 'react';
move this to the top of imports

2024-03-18 14:55 UTC, davidlougheed commented on src/js/index.tsx
> +    console.log('lang', lang);
this is a new console log; was it for debugging, or is it for a more permanent logging purpose (in which case, it should be assigned a level; `console.debug`)

2024-03-18 14:55 UTC, davidlougheed commented on src/public/locales/fr/default_translation_fr.json
> +  "Sign Out": "Se déconnecter"
inconsistent capitalization between french sign in/out - lowercase for "connecter" is probably better

2024-03-18 19:04 UTC, davidlougheed requested changes

2024-03-18 19:04 UTC, davidlougheed commented on src/js/features/beacon/beaconConfig.store.ts
> +    const beaconInfoEndpoint = BEACON_URL + '/overview';
this declaration can be a constant outside of the function

2024-03-19 15:22 UTC, davidlougheed approved these changes
lgtm

2024-03-19 15:26 UTC, merged