[WIP] Site sider
bento-platform/bento_public pull request #162
Opened 2024-05-16 18:20 UTC by SanjeevLakhwani

2024-05-16 19:46 UTC, davidlougheed requested changes
needs to account for custom logos

remove extra beacon file

2024-05-16 19:46 UTC, davidlougheed commented on src/js/components/SiteSider.tsx
> +import { useAppSelector, useTranslationDefault } from '@/hooks';
please consolidate and order these inputs from `react-*` to `@ant-design*` to `@` imports to local imports

2024-05-16 19:46 UTC, davidlougheed commented on src/styles.css
> +}
missing trailing newline

2024-05-17 14:39 UTC, gsfk reviewed
Side menu much prettier than the old tabs!

Perhaps a little late for this question, but what's the advantage of a "slider" over a simple side menu? I would think the main use case would be the ability to show a smaller menu when the sceen is smaller, but this pr doesn't do that.

2024-05-23 14:29 UTC, gsfk reviewed
I'm not totally sold on the new header text... although the text appears in the same spot for each page, the page layout isn't consistent. Overview and Provenance are aligned with the component below them: 

![Screenshot from 2024-05-23 10-15-24](https://github.com/bento-platform/bento_public/assets/18051642/a023c59a-69b8-4a28-ad4c-ea5a65ba0a75)

... but Search & Beacon are not: 
![gap](https://github.com/bento-platform/bento_public/assets/18051642/5cad6e11-6f46-4451-b9b0-63cff37d49d3)

I also just find them ugly... I know that's not a particularly helpful comment. I wonder if this text wouldn't be better off in the header? Not sure.

![header](https://github.com/bento-platform/bento_public/assets/18051642/0623178e-1341-4977-b879-b84e34b5e248)

2024-06-03 20:09 UTC, davidlougheed requested changes
aesthetically, I think the bright white header text/button outlines are bit too harsh on the dark header background, but the visual hierarchy with the new sidebar being context for what page/project/dataset we are on works quite well.

maybe the contents of the sidebar should be sticky, so that we can change pages even if scrolled-down?

weird horizontal overflow/scroll, only on overview page on small screen (14" laptop)
<img width="792" alt="Screenshot 2024-06-03 at 4 04 06 PM" src="https://github.com/bento-platform/bento_public/assets/357970/4f14ec4b-26e1-4436-916e-d19b9afa3396">

2024-06-03 20:09 UTC, davidlougheed commented on src/js/components/SiteSider.tsx
> +  console.log({ currentPage });
make this a proper debug log with information about whats being logged or remove it

2024-06-03 20:09 UTC, davidlougheed commented on src/js/hooks.ts
> +  const validPages = ['overview', 'search', 'beacon', 'provenance'];
I don't like that this is hard-coded in multiple places...

2024-06-03 20:09 UTC, davidlougheed commented on src/js/hooks.ts
> +export const getCurrentPage = (): string => {
technically not a hook - doesn't use `use` prefix and window.location/location/pathname don't trigger re-render

2024-06-03 20:09 UTC, davidlougheed commented on src/js/hooks.ts
> +  const location = window.location;
weird re-assignment to do

2024-06-03 20:09 UTC, davidlougheed commented on src/styles.css
> +.logo-container.collapsed {
is this still needed?

2024-06-04 15:07 UTC, gsfk reviewed
So....
- top of the screen is black but side is white?
- current tab indicated from menu only?

... I wasn't sure where we landed on either of these issues. 

The "Search" page does not behave consistently: if you load the main page and click Search it shows an overview, but it you load `/search` it shows zero results.

2024-06-05 18:00 UTC, SanjeevLakhwani commented
> * top of the screen is black but side is white?
This was done to correspond with the mock-up created previously .The hierarchy was changed from header now being the top-level component instead of the sidebar and the colors try to correspond with that. 
> * current tab indicated from menu only?
Yes as to reduce some clutter. The icons on the sidebar should now correctly represent what page one is on by being highlighted

2024-06-05 20:27 UTC, davidlougheed requested changes
fix responsivity

2024-06-06 16:14 UTC, davidlougheed requested changes

2024-06-06 18:36 UTC, SanjeevLakhwani commented on src/js/components/SiteHeader.tsx
> +                marginLeft: '-15px',
Header has a default y padding of 50px on both sides, I thought the logo looked better moved back a lil but on a second thought doesn't matter much so removed it now

2024-06-06 18:53 UTC, davidlougheed approved these changes
need to fix z-stacking / side-scrolling issues with narrow windows

![image](https://github.com/bento-platform/bento_public/assets/357970/5dd2c081-a90e-415f-89b2-47c1afbcf21b)

2024-06-06 18:54 UTC, davidlougheed requested changes
selected wrong opt

2024-06-10 19:41 UTC, gsfk commented
Looking good, I like the sticky menu. 

There's a conceptual change with chart width and the "manage charts" settings, the width setting is now really a max-width setting.

2024-06-10 19:42 UTC, gsfk reviewed
Looking good, I like the sticky menu.

There's a conceptual change with chart width and the "manage charts" settings, the width setting is now really a max-width setting.

2024-06-14 17:06 UTC, gsfk approved these changes

2024-06-14 17:07 UTC, davidlougheed reviewed
how will the new file for branding work with our existing instances that replace the logo?

2024-06-17 13:51 UTC, SanjeevLakhwani commented
> how will the new file for branding work with our existing instances that replace the logo?

I corrected the filenames to match the previous, so it should be the same as before

2024-06-17 21:00 UTC, davidlougheed requested changes
icon on both left and right of portal button - on left, the old icon; on right, the link icon. otherwise looks good i think.

2024-06-19 17:39 UTC, gsfk reviewed
The results pane jumps when switching between "Search" and "Beacon", it should be in the same place.

2024-06-19 19:48 UTC, merged