New translations
bento-platform/bento_public pull request #166
Opened 2024-06-13 15:50 UTC by SanjeevLakhwani

2024-06-13 15:55 UTC, davidlougheed requested changes

2024-06-13 15:55 UTC, davidlougheed commented on src/js/components/Search/SearchResultsPane.tsx
> +  const translateMap = ({ x, y }: { x: string; y: number }) => ({ x: t(x), y });
passed to a component, so wrap in a `useCallback`

2024-06-13 15:55 UTC, davidlougheed commented on src/public/locales/fr/translation_fr.json
> +  "I have slight problems in walking about": "J’ai quelques problèmes à marcher",
for the terms that come from BQC19, use the BQC19 translations instead of machine translation.

2024-06-13 15:55 UTC, davidlougheed commented on src/public/locales/en/translation_en.json
> +  "Smoking status": "Smoking status",
why are both of these keys needed?

2024-06-17 14:14 UTC, SanjeevLakhwani commented on src/public/locales/en/translation_en.json
> +  "Smoking status": "Smoking status",
was a mistake removed it

2024-06-17 19:36 UTC, davidlougheed submitted a review, later dismissed
please make the translations have the same indent level

2024-06-20 18:22 UTC, v-rocheleau requested changes
Looks good, only noticed an issue with the "in" translation.
By default we translate "in" => "dans", but this is grammatically incorrect in the Search context, where we have:

- "Age (in years)" => "Âge(dans years)"
   - should be "Âge (en années)"
- "Lab Test Results (in mg/L) => Résultats des tests de laboratoire (dans mg/L)"
   - should be "Résultats des tests de laboratoire (en mg/L)"

2024-06-26 17:09 UTC, v-rocheleau requested changes
Close to being ok, there is still an issue with the "years" translation however:
![image](https://github.com/bento-platform/bento_public/assets/122313248/5f75c372-273a-4431-92d7-72056d805fc0)
This should be "(en années)"

2024-07-09 17:29 UTC, v-rocheleau approved these changes
Kept having the "en years" issue because I was using Bento's default translation file in `lib/public/translations`. After merging this we should update the default translations in the Bento repo.

2024-07-15 19:28 UTC, merged