[WIP] feat(search): show individual match results when available
bento-platform/bento_public pull request #191
Opened 2024-09-27 18:07 UTC by davidlougheed

2024-09-27 19:35 UTC, gsfk reviewed
Works as expected. I'm assuming more stuff will be filled in later. 

I had to click "Sign in" on the portal page that popped up, even though I was already signed in, although I wasn't forced to login a second time. But I assume this too won't be an issue later.

2024-09-27 19:39 UTC, davidlougheed commented
yeah the idea is to have something relatively straightforward to show that we're moving towards integration of auth and gradual permissions, and to slowly merge it with beacon/the explore page as we go.

2024-09-30 15:01 UTC, v-rocheleau requested changes

2024-09-30 15:01 UTC, v-rocheleau commented on src/styles.css
It was not clear to me at first that the `Individuals` element was clickable, I think a hover class would help with that.

2024-09-30 15:05 UTC, davidlougheed commented on src/js/components/Search/SearchResults.tsx
> +  const individualMatches = useAppSelector((state) => state.query.individualMatches);
i agree

2024-09-30 15:06 UTC, davidlougheed commented on src/styles.css
sounds good!

2024-09-30 16:07 UTC, v-rocheleau approved these changes
LGTM!

2024-09-30 16:55 UTC, merged