added types to overview
bento-platform/bento_public pull request #69
Opened 2023-04-03 17:13 UTC by SanjeevLakhwani

2023-04-04 17:39 UTC, v-rocheleau requested changes

2023-04-04 17:39 UTC, v-rocheleau commented on src/js/hooks.ts
Didn't know about this, pretty cool. 
We could add a comment linking to the react-redux doc [section](https://react-redux.js.org/using-react-redux/usage-with-typescript#define-typed-hooks) for this, since we will have to get acquainted with typed hooks once we merge.

2023-04-04 17:39 UTC, v-rocheleau commented on src/js/components/Overview/PublicOverview.tsx
> -                <OverviewSection index={i} title={sectionTitle} chartData={charts} />
Why remove index here?

2023-04-04 21:37 UTC, SanjeevLakhwani commented on src/js/components/Overview/PublicOverview.tsx
> -                <OverviewSection index={i} title={sectionTitle} chartData={charts} />
OverviewSection doesn't use index

2023-04-05 15:40 UTC, v-rocheleau approved these changes

2023-04-05 16:34 UTC, merged