[WIP] Delegate max_query_parameters config to katsu
bento-platform/bento_public pull request #75
Opened 2023-04-18 05:30 UTC by brouillette

- bento_public now avoids duplicate configuration and fetches the `max_query_parameters` field from katsu when needed

2023-04-25 13:10 UTC, davidlougheed requested changes
this adds some empty files in `www/public`, what are those for?

2023-04-25 13:10 UTC, davidlougheed commented on main.go
> +		fmt.Println("for fun")
rm

2023-04-25 16:25 UTC, brouillette commented on main.go
> +		fmt.Println("for fun")
whoopsies

2023-05-02 14:36 UTC, v-rocheleau approved these changes
lgtm

2023-05-02 20:21 UTC, merged