Feature/about translation ts
bento-platform/bento_public pull request #76
Opened 2023-05-03 14:57 UTC by noctillion

Description:
This PR adds support for translating the about.html content in the Overview tab. The changes introduced include:

Changes:

Basic templates eng_about.html and fr_about.html
Fetching both English and French versions of x_about.html content using async thunk.
Dynamically rendering the x_about.html content in the Overview tab based on the active language.

2023-05-03 17:38 UTC, v-rocheleau requested changes

2023-05-03 17:38 UTC, v-rocheleau commented on src/js/constants/contentConstants.ts
> +export const partialAboutUrl = '/public/';
Replace `'/public/'` with `'/public'`. All of our url constants have no trailling slash.

2023-05-03 17:38 UTC, v-rocheleau commented on src/js/features/content/content.store.ts
> +    .get(`${partialAboutUrl}fr_about.html`)
Add `/` before file name once partialAboutUrl has no trailling slash

2023-05-03 17:38 UTC, v-rocheleau commented on src/js/features/content/content.store.ts
>  };
I would change the ContentState shape for:
```typescript
export type ContentState = {
  isFetchingAbout: boolean;
  about: {[key: string]: string}
};

const initialState: ContentState = {
  isFetchingAbout: true,
  about: {
    en: "",
    fr: ""
  }
};
```
This way, we can get the about content by key and avoid the if blocks in PublicOverview's useEffect:
```typescript
  const { isFetchingAbout, about } = useAppSelector((state) => state.content);

  const [aboutContent, setAboutContent] = useState('');

  useEffect(() => {
    const activeLanguage = i18n.language;
    const activeAbout = about[activeLanguage];
    setAboutContent(activeAbout);
  }, [i18n.language, about]);
```
Like this we won't have to change the PublicOverview component if we add new languages

2023-05-03 19:34 UTC, noctillion commented
Thanks for the review and excellent suggestions!

2023-05-03 20:42 UTC, v-rocheleau requested changes

2023-05-03 20:42 UTC, v-rocheleau commented on src/js/features/content/content.store.ts
> +      state.about.fr = payload.fr;
State update can be simplified with:
```typescript
state.about = {...payload};
```

2023-05-04 18:00 UTC, v-rocheleau commented on src/js/features/content/content.store.ts
> +      state.about = { ...payload}
Missing semicolon

2023-05-04 20:26 UTC, v-rocheleau approved these changes

2023-05-11 14:38 UTC, merged