v0.10.3 rc-1
bento-platform/bento_public pull request #80
Opened 2023-05-17 19:11 UTC by brouillette

Contains
- translation patches
- backend optimizations

2023-05-17 19:19 UTC, davidlougheed requested changes
one minor change. also, can you rename the PR from a version to a description of what this PR is doing and undraft it? we may or may not make this v0.12 depending on if we also get Beacon UI merged.

2023-05-17 19:19 UTC, davidlougheed commented on main.go
> +		fmt.Println("'publicOverview' not found or expired in 'katsuCache - fetching")
minor - missing closing single quote after katsuCache

2023-05-18 19:20 UTC, davidlougheed approved these changes
lgtm

2023-05-19 18:03 UTC, gsfk reviewed
No issues for me, other than a small merge conflict with my own PR, which shouldn't be to hard to manage.

2023-05-20 18:45 UTC, merged